export enum Item {
  // Equipment
  KokiriSword,
  BiggoronSword,
  HylianShield,
  MirrorShield,
  GoronTunic,
  ZoraTunic,
  IronBoots,
  HoverBoots,
  // Items
  DekuSticks,
  DekuNuts,
  Bombs,
  Bow,
  FireArrows,
  DinsFire,
  Slingshot,
  Ocarina,
  Bombchus,
  Hookshot,
  Longshot,
  IceArrows,
  FaroresWind,
  Boomerang,
  LensOfTruth,
  MagicBeans,
  MegatonHammer,
  LightArrows,
  NayrusLove,
  RutosLetter,
  Bottle,
  SkullMask,
  ClaimCheck,
  // Other
  Magic,
  GoronBracer,
  SilverGauntlets,
  GoldGauntlets,
  SilverScale,
  GoldScale,
  // Songs
  ZeldasLullaby,
  EponasSong,
  SariasSong,
  SunsSong,
  SongOfTime,
  SongOfStorms,
  MinuetOfForest,
  BoleroOfFire,
  SerenadeOfWater,
  RequiemOfSpirit,
  NocturneOfShadow,
  PreludeOfLight,
  ScarecrowSong,
  // Stones
  KokiriEmerald,
  GoronRuby,
  ZoraSapphire,
  // Medallions
  LightMedallion,
  ForestMedallion,
  FireMedallion,
  WaterMedallion,
  ShadowMedallion,
  SpiritMedallion,
  // Dungeon Medallions
  DekuTreeMedallion,
  DodongosCavernMedallion,
  JabuJabuMedallion,
  ForestTempleMedallion,
  FireTempleMedallion,
  WaterTempleMedallion,
  ShadowTempleMedallion,
  SpiritTempleMedallion,
}
